x1 <- list(1.1, 2.2, 3.3, 4.4)
listToVector(x1)
x2 <- list()
listToVector(x2)
listToVector(x2, empty=numeric(0))
listToVector(x2, empty=NA)
x3 <- list(1.1, 2.2, 3L)
listToVector(x3)
listToVector(x3, convert.int=TRUE)
x4 <- list(1.1, 2.2, c(3.3, 4.4))
listToVector(x4)
x5 <- list(NA, 1.1, 2.2)
listToVector(x5)
listToVector(x5, na.action="warn")
x6 <- list(NA, 1L, NA, 2.5)
listToVector(x6)
listToVector(x6, convert.int=TRUE)
listToVector(x6, convert.int=TRUE, na.action="warn")
listToVector(x6, convert.int=TRUE, na.action="omit")
listToVector(x6, convert.int=TRUE, na.action="ignore")
x7 <- list(1.5, NULL, 2.5)
listToVector(x7)
listToVector(x7, null.action="omit")
listToVector(x7, null.action="warn")
x8 <- list("yes", "no")
listToVector(x8)
listToVector(x8, na.action="omit")
listToVector(x8, null.action="omit")
x9 <- list("yes", NA, "no")
listToVector(x9)
listToVector(x9, na.action="ignore")
x10 <- list(TRUE, FALSE)
listToVector(x10)
x11 <- list(TRUE, NA, FALSE)
listToVector(x11)
listToVector(x11, na.action="ignore")
